### ISSUE TITLE
Consistency check of formalization does not work

### ISSUE THREAD

**Issue by terezanovot** [normativeai/backend#34] opened 2019-06-08 11:00 UTC
If running consistency check of formalization (only first two sentences) in Rome regulation - annot., the errror message shows:
Error: Internal server error Error: Command failed: ./mleancop.sh problem8768354

**Comment by shaolintl** [comment] 2019-06-11 09:22
duplicate of #27

**Closed by shaolintl** 2019-06-11 09:22 UTC
Labels: duplicate
